version: '3'

services:
#  server:
#    image: golang:1.11-alpine3.7
#    links:
#    - "minio:minio"
##    - "mysql:mysql"
#    volumes:
#    - uploads:$IMAGINATION_UPLOADS_DIR
#    - .:$IMAGINATION_GO_PROJECT_DIR
#    working_dir: "$IMAGINATION_GO_PROJECT_DIR"
#    command: go run cmd/main.go
#    ports:
#    - "8080:8080"
#    env_file:
#    - .env

  mysql:
    image: mysql
    volumes:
    - db_data:/var/lib/mysql
    -
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "topsecret"

volumes:
  db_data: {}